### PR TITLE
Lua>=5.2 compatibility (see mpx/#22)

### PR DESCRIPTION
**Pull request by msva**

### CODE REVIEW

**Comment by agentzh** [comment]
@cloudwu Thank you for the patch! I'll look into it shortly :)

**Comment by agentzh** [comment]
@cloudwu Are you cool with merging into this fork?

**Comment by cloudwu** [comment]
@agentzh ok

**Comment by agentzh** [comment]
@cloudwu Thanks.

**Comment by chipitsine** [comment]
should we extend travis-ci matrix to add other version of Lua ?

**Comment by agentzh** [comment]
@chipitsine As long as we already support them :)

**Comment by korialuo** [comment]
@agentzh  Lua5.3 integer compatibility is quite neccesary. When could you merge this pr?

**Comment by leafo** [comment]
Note that I merged #49 which lets it build on all modern version of Lua, but integer support was not part of that change as I wanted to keep the changes minimal. The changes here will have to be rebased on top of that.

I also added a new test suite for all versions of Lua with #50 which should make it easier to get these changes in with confidence!

**Pull request closed without merging**
