### PR TITLE
Add configuration option to disable forward slash escaping

### PR DESCRIPTION
**Pull request by spacewander**
This PR is based on #59. Thanks @exjesper for the original patch. I just remove the detection from the hot path to make it a little faster when the escape is disabled.

### CODE REVIEW

**Comment by agentzh** [comment]
I'm not sure about this one since it leads to invalid JSON output. See json.org for the syntax spec for JSON.

**Comment by agentzh** [comment]
OK, I had a closer look and it seems escaping `/` is optional, not mandatory. Then it's fine.

**Comment by spacewander** [comment]
@agentzh 
Also add doc for the new method.

**Comment by exjesper** [comment]
Thanks @spacewander this looks better :+1: , I'll close my PR.

**Pull request merged**
